### ISSUE TITLE
Type error: Property 'quantityLimitPerTransaction' does not exist on type

### ISSUE THREAD

**Issue by devburaq** [thirdweb-example/erc721#13]
Hello @jarrodwatts 

I'm getting this error now too when exporting! Any idea?
Thanks

`./pages/index.tsx:124:47
Type error: Property 'quantityLimitPerTransaction' does not exist on type '{ metadata?: string | undefined; snapshot?: { price?: string | undefined; currencyAddress?: string | undefined; address: string; maxClaimable: string; }[] | null | undefined; maxClaimableSupply: string; ... 8 more ...; currencyMetadata: { ...; }; }'.

  122 |                       quantity >=
  123 |                       parseInt(
> 124 |                         activeClaimCondition?.quantityLimitPerTransaction || "0"
      |                                               ^
  125 |                       )
  126 |                     }
  127 |                   >`

**Comment by 3web3** [comment]
Edit: I guess with "availableSupply" the problem is solved.

`activeClaimCondition?.availableSupply`

**Comment by jarrodwatts** [comment]
Thanks @3web3 - we're working on fixing this. We changed claim conditions behaviour recently.

Learn more: https://blog.thirdweb.com/announcing-improved-claim-conditions/

**Comment by devburaq** [comment]
> Thanks @3web3 - we're working on fixing this. We changed claim conditions behaviour recently.
> 
> Learn more: https://blog.thirdweb.com/announcing-improved-claim-conditions/

Hello @jarrodwatts,

When I tried with "availableSupply", I was able to get build without any problem. I wanted to share for those who have the same problem.

Thank you for your interest.
