### ISSUE TITLE
Error claiming NFTs

### ISSUE THREAD

**Issue by jharrower84** [thirdweb-example/erc721#18]
Error: Error claiming NFTs

**Comment by jharrower84** [comment]
Not just my build but the example too. New version of a library somewhere?

**Comment by kien-ngo** [comment]
@jharrower84 Are you still having issues with this repo? I'm happy to take a look!

**Comment by warengonzaga** [comment]
Looks stale to me, if you wish to continue @jharrower84 feel free to reply to this issue. Thanks for the help @kien-ngo
