### ISSUE TITLE
Adding wallet connect

### ISSUE THREAD

**Issue by rab554628** [thirdweb-example/erc721#4]
This is very helpful.
Anyone, please add wallet connect and ability to mint more than one NFTs to this module, thanks.

**Comment by jarrodwatts** [comment]
To change from MetaMask to wallet connect you can switch `useMetamask()` to `useWalletConnect`

**Comment by nachoiacovino** [comment]
Would be fixed when #7 gets merged

**Comment by rab554628** [comment]
Thanks a lot guys, you are the best.
