### ISSUE TITLE
add a configuration for custom RPC node

### ISSUE THREAD

**Issue by warengonzaga** [thirdweb-example/erc721#9]
Have a way to configure or customize the RPC node in the code.

**Comment by jarrodwatts** [comment]
This shouldn't be required anymore. Our SDK no longer uses public RPCs and we provide one for users by default.

If you want to use your own RPC URL please modify the ThirdwebProvider: https://portal.thirdweb.com/react/react.thirdwebproviderprops

**Comment by vvarl0cks** [comment]
> This shouldn't be required anymore. Our SDK no longer uses public RPCs and we provide one for users by default.
> 
> If you want to use your own RPC URL please modify the ThirdwebProvider: https://portal.thirdweb.com/react/react.thirdwebproviderprops

`Page Not Found`
any updates? thanks mate.
